version: '3.3'

services:
    python-cli:
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
            - './:/app'
        stdin_open: true
        working_dir: /app